# Generated by Django 4.2.10 on 2026-07-15 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(help_text='Identificador libre del tipo de accion (ej. RESERVA_CREAR, INCIDENCIA_CREAR).', max_length=50)),
                ('payload', models.JSONField(help_text='Parametros de la accion que el agente ejecutaria al confirmarse.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de confirmacion'), ('CONFIRMADA', 'Confirmada, pendiente de ejecucion'), ('EJECUTADA', 'Ejecutada'), ('RECHAZADA', 'Rechazada por el usuario'), ('EXPIRADA', 'Expirada sin confirmar')], default='PENDIENTE', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateTimeField(blank=True, help_text='Si se define y se supera sin confirmar, la accion pasa a EXPIRADA.', null=True)),
                ('resultado', models.JSONField(blank=True, help_text='Salida de la ejecucion real (la llena el ejecutor de HU-01.1 al procesar la confirmacion).', null=True)),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_agente_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(help_text='Usuario para quien el agente propuso la accion.', on_delete=django.db.models.deletion.CASCADE, related_name='acciones_agente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Accion del agente',
                'verbose_name_plural': 'Acciones del agente',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
