# Generated by Django 4.2.10 on 2026-07-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaction',
            name='estado_previo',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente de confirmacion'), ('CONFIRMADA', 'Confirmada, pendiente de ejecucion'), ('EJECUTADA', 'Ejecutada'), ('RECHAZADA', 'Rechazada por el usuario'), ('EXPIRADA', 'Expirada sin confirmar')], help_text='Estado inmediatamente anterior a `estado`, para poder ver la ultima transicion sin una tabla de historial aparte.', max_length=15, null=True),
        ),
    ]
