# Generated by Django 4.2.10 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agente", "0002_agentaction_estado_previo"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentaction",
            name="backend_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="confirmation_method",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="error_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="executed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="idempotency_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="requires_confirmation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="thread_id",
            field=models.CharField(blank=True, db_index=True, max_length=36),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="tool_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agentaction",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("NO_INICIADA", "No iniciada"),
                    ("VERIFICADA", "Verificada"),
                    ("FALLIDA", "Fallida"),
                    ("DESCONOCIDA", "Desconocida"),
                ],
                default="NO_INICIADA",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="agentaction",
            constraint=models.UniqueConstraint(
                fields=("usuario", "idempotency_key"),
                name="unique_agent_action_idempotency_per_user",
            ),
        ),
    ]
