# Generated by Django 4.2.10 on 2025-06-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Incendio', 'Incendio'), ('Sismo', 'Sismo'), ('Seguridad', 'Seguridad'), ('Salud', 'Salud'), ('Aviso importante', 'Aviso importante'), ('Reunión', 'Reunión')], max_length=50)),
                ('descripcion', models.TextField()),
                ('usuario', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
