# Generated by Django 4.2.10 on 2025-06-02 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha']},
        ),
        migrations.RenameField(
            model_name='alerta',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='alerta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='alerta',
            name='atendido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='enviado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_enviadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='alerta',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
