# Generated by Django 4.2.10 on 2026-03-18 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
        ('alertas', '0002_alter_alerta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AddField(
            model_name='alerta',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='viviendas.edificio'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='viviendas.vivienda'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo', 'estado'], name='alertas_ale_tipo_36edc4_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', '-fecha'], name='alertas_ale_estado_79e37e_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['edificio', '-fecha'], name='alertas_ale_edifici_73166a_idx'),
        ),
    ]
