# Generated by Django 4.2.10 on 2026-03-25 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
        ('alertas', '0003_alter_alerta_options_alerta_edificio_alerta_vivienda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('general', 'General'), ('mantenimiento', 'Mantenimiento'), ('reunion', 'Reunión'), ('evento', 'Evento'), ('reglas', 'Reglas y Normativas'), ('financiero', 'Financiero')], default='general', max_length=20)),
                ('fijado', models.BooleanField(default=False, help_text='Anuncios fijados aparecen primero')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='viviendas.edificio')),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'ordering': ['-fijado', '-fecha_creacion'],
                'indexes': [models.Index(fields=['edificio', '-fecha_creacion'], name='alertas_anu_edifici_c5f914_idx'), models.Index(fields=['activo', 'edificio'], name='alertas_anu_activo_4b1537_idx')],
            },
        ),
    ]
