# Generated by Django 4.2.10 on 2026-03-25 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertas', '0004_add_anuncio_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='es_votacion',
            field=models.BooleanField(default=False, help_text='Si es True, este anuncio tiene una encuesta adjunta'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='fecha_cierre_votacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora límite para votar. Null = sin límite.', null=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='voto_anonimo',
            field=models.BooleanField(default=False, help_text='Si es True, no se muestra quién votó'),
        ),
        migrations.CreateModel(
            name='OpcionVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='alertas.anuncio')),
            ],
            options={
                'verbose_name': 'Opción de Voto',
                'verbose_name_plural': 'Opciones de Voto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='alertas.opcionvoto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_anuncios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
                'unique_together': {('opcion', 'usuario')},
            },
        ),
    ]
