# Generated by Django 4.2.10 on 2026-07-13 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0005_add_votacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('ascensores', 'Ascensores'), ('vidrios', 'Vidrios'), ('limpieza', 'Limpieza'), ('jardineria', 'Jardinería'), ('normas', 'Incumplimiento de normas'), ('otro', 'Otro')], help_text='Categoría de la incidencia; la asigna el agente al clasificar.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='duplicado_de',
            field=models.ForeignKey(blank=True, help_text='Si esta alerta es un duplicado, apunta a la alerta principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='alertas.alerta'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='prioridad',
            field=models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', help_text='Prioridad asignada por el agente; determina timeout y orden.', max_length=10),
        ),
        migrations.AddField(
            model_name='alerta',
            name='requiere_atencion_manual',
            field=models.BooleanField(default=False, help_text='True cuando el agente agotó la escalera de asignación.'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('Incendio', 'Incendio'), ('Sismo', 'Sismo'), ('Seguridad', 'Seguridad'), ('Salud', 'Salud'), ('Aviso importante', 'Aviso importante'), ('Reunión', 'Reunión'), ('Incidencia', 'Incidencia')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['edificio', 'categoria', 'estado'], name='alertas_ale_edifici_2ec68d_idx'),
        ),
    ]
