# Generated by Django 4.2.10 on 2026-07-13 22:37

from django.db import migrations


def backfill_edificio(apps, schema_editor):
    """
    Rellena Alerta.edificio para alertas antiguas que quedaron en NULL
    (creadas antes de que perform_create asignara edificio).

    Necesario porque los filtros de Gerente ahora usan alerta.edificio:
    sin este backfill, las alertas viejas sin edificio desaparecerían del
    dashboard del gerente. Se resuelve el edificio desde el autor.
    """
    Alerta = apps.get_model('alertas', 'Alerta')

    for alerta in Alerta.objects.filter(edificio__isnull=True).select_related('enviado_por'):
        user = alerta.enviado_por
        edificio_id = None
        # Mismo orden de prioridad que _resolver_edificio_usuario, pero con
        # los modelos históricos (no se pueden importar los reales en migración).
        residente = getattr(user, 'residente', None)
        if residente and residente.vivienda_id:
            edificio_id = residente.vivienda.edificio_id
        if not edificio_id:
            vigilante = getattr(user, 'vigilante', None)
            if vigilante:
                edificio_id = vigilante.edificio_id
        if not edificio_id:
            gerente = getattr(user, 'gerente', None)
            if gerente:
                edificio_id = gerente.edificio_id
        if not edificio_id:
            empleado = getattr(user, 'empleado', None)
            if empleado:
                edificio_id = empleado.edificio_id

        if edificio_id:
            alerta.edificio_id = edificio_id
            alerta.save(update_fields=['edificio'])


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0006_alerta_categoria_alerta_duplicado_de_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_edificio, migrations.RunPython.noop),
    ]
