# Generated by Django 4.2.10 on 2025-05-14 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accesos', '0001_initial'),
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visita',
            name='residente_autoriza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas_autorizadas', to='viviendas.residente'),
        ),
        migrations.AddField(
            model_name='visita',
            name='vivienda_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='viviendas.vivienda'),
        ),
        migrations.AddField(
            model_name='movimientoresidente',
            name='residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='viviendas.residente'),
        ),
    ]
