# Generated by Django 4.2.10 on 2026-03-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='qr_nonce',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='visita',
            name='qr_usado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visita',
            name='qr_usado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
