# Generated by Django 4.2.10 on 2026-03-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0003_visita_qr_nonce_visita_qr_usado_visita_qr_usado_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoresidente',
            options={'ordering': ['-fecha_hora_entrada', '-fecha_hora_salida'], 'verbose_name': 'Movimiento de Residente', 'verbose_name_plural': 'Movimientos de Residentes'},
        ),
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-fecha_hora_entrada'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AddIndex(
            model_name='movimientoresidente',
            index=models.Index(fields=['residente', '-fecha_hora_entrada'], name='accesos_mov_residen_19e816_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoresidente',
            index=models.Index(fields=['-fecha_hora_salida'], name='accesos_mov_fecha_h_4c08fc_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['vivienda_destino', '-fecha_hora_entrada'], name='accesos_vis_viviend_2545a9_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['residente_autoriza', '-fecha_hora_entrada'], name='accesos_vis_residen_43b460_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['qr_usado'], name='accesos_vis_qr_usad_29def2_idx'),
        ),
    ]
