# Generated by Django 4.2.10 on 2026-07-15 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
        ('accesos', '0004_alter_movimientoresidente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Puerta principal'), ('EDIFICIO', 'Puerta de edificio'), ('VIVIENDA', 'Puerta de vivienda')], max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True, default='', help_text='URL del dispositivo (ESP32/relé). Vacío = modo software.')),
                ('edificio', models.ForeignKey(blank=True, help_text='Requerido si el tipo es Puerta de edificio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puertas', to='viviendas.edificio')),
                ('vivienda', models.ForeignKey(blank=True, help_text='Requerido si el tipo es Puerta de vivienda.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puertas', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Puerta',
                'verbose_name_plural': 'Puertas',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AperturaPuerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('exito', models.BooleanField(default=True)),
                ('detalle', models.CharField(blank=True, default='', max_length=200)),
                ('puerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='accesos.puerta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_puerta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura de puerta',
                'verbose_name_plural': 'Aperturas de puertas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['puerta', '-fecha_hora'], name='accesos_ape_puerta__8436f3_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='accesos_ape_usuario_750956_idx')],
            },
        ),
    ]
