# Generated by Django 4.2.10 on 2026-07-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_puerta_aperturapuerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='puerta',
            name='habilitada_para_demo',
            field=models.BooleanField(default=False, help_text='Si está apagado, la apertura remota queda bloqueada (demo controlada).'),
        ),
    ]
