# Generated by Django 4.2.10 on 2026-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0005_puerta_aperturapuerta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-id'], 'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AddField(
            model_name='visita',
            name='cantidad_personas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('RESERVADA', 'Reservada, esperando llegada'), ('CONFIRMADA', 'Ingreso confirmado'), ('EXPIRADA', 'Expirada sin confirmar'), ('CANCELADA', 'Cancelada')], default='CONFIRMADA', max_length=12),
        ),
        migrations.AddField(
            model_name='visita',
            name='fecha_visita',
            field=models.DateField(blank=True, help_text='Solo si es una reserva a futuro; vacio = registro inmediato (comportamiento historico).', null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Fin de la ventana de validez del QR.', null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Inicio de la ventana de validez del QR.', null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='fecha_hora_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
