# Generated by Django 4.2.10 on 2026-07-17 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0006_alter_visita_options_visita_cantidad_personas_and_more'),
        ('accesos', '0006_puerta_habilitada_para_demo'),
    ]

    operations = [
    ]
