# Generated by Django 4.2.10 on 2026-07-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesos', '0008_access_idempotency_and_hardware_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='decision_residente_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='foto_visitante',
            field=models.ImageField(blank=True, null=True, upload_to='visitas/llegadas/'),
        ),
        migrations.AddField(
            model_name='visita',
            name='llegada_reportada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='notificacion_estado',
            field=models.CharField(
                default='NO_REGISTRADA',
                help_text='REGISTRADA_LOCAL indica que la app puede obtenerla por polling.',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='visita',
            name='estado',
            field=models.CharField(
                choices=[
                    ('RESERVADA', 'Reservada, esperando llegada'),
                    ('PENDIENTE_APROBACION', 'Llegada reportada, esperando aprobación'),
                    ('CONFIRMADA', 'Ingreso confirmado'),
                    ('RECHAZADA', 'Ingreso rechazado por el residente'),
                    ('EXPIRADA', 'Expirada sin confirmar'),
                    ('CANCELADA', 'Cancelada'),
                ],
                default='CONFIRMADA',
                max_length=24,
            ),
        ),
    ]
