# Generated by Django 4.2.10 on 2025-05-31 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
        ('usuarios', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePotencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha_contacto', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente Potencial',
                'verbose_name_plural': 'Clientes Potenciales',
                'permissions': [('ver_cliente_potencial', 'Puede ver clientes potenciales')],
            },
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gerentes', to='viviendas.edificio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gerente',
                'verbose_name_plural': 'Gerentes',
            },
        ),
    ]
