# Generated by Django 4.2.10 on 2025-06-01 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
        ('usuarios', '0004_clientepotencial_alter_rol_nombre_gerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vigilante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vigilantes', to='viviendas.edificio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vigilante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
