# Generated by Django 4.2.10 on 2026-03-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_clientepotencial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='credenciales_expiran',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora en que expiran las credenciales temporales', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión'),
        ),
    ]
