# Generated by Django 4.2.10 on 2026-07-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0004_condominio_edificio_condominio'),
        ('usuarios', '0007_usuario_credenciales_expiran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerente',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gerentes', to='viviendas.condominio'),
        ),
    ]
