# Generated by Django 4.2.10 on 2025-05-22 01:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('presupuesto_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('color', models.CharField(default='#3498db', help_text='Código de color HEX para gráficos', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gastos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('BIMESTRAL', 'Bimestral'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual'), ('UNICA', 'Única vez')], default='MENSUAL', max_length=15)),
                ('aplica_recargo', models.BooleanField(default=True, help_text='Indica si se aplican recargos por mora')),
                ('porcentaje_recargo', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de recargo mensual por pago tardío', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Cuota',
                'verbose_name_plural': 'Conceptos de Cuotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('pagada', models.BooleanField(default=False)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuotas', to='financiero.conceptocuota')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('OTRO', 'Otro')], max_length=15)),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia, cheque o transacción', max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de verificación'), ('VERIFICADO', 'Verificado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='pagos/comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PagoCuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiero.cuota')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financiero.pago')),
            ],
            options={
                'verbose_name': 'Detalle Pago-Cuota',
                'verbose_name_plural': 'Detalles Pago-Cuota',
                'unique_together': {('pago', 'cuota')},
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='cuotas',
            field=models.ManyToManyField(related_name='pagos', through='financiero.PagoCuota', to='financiero.cuota'),
        ),
        migrations.AddField(
            model_name='pago',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='residente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='viviendas.residente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='verificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='vivienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='viviendas.vivienda'),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='gastos/comprobantes/')),
                ('factura', models.CharField(blank=True, help_text='Número de factura o recibo', max_length=100)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de pago'), ('PAGADO', 'Pagado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('tipo_gasto', models.CharField(choices=[('ORDINARIO', 'Gasto Ordinario'), ('EXTRAORDINARIO', 'Gasto Extraordinario'), ('MANTENIMIENTO', 'Mantenimiento'), ('SERVICIO', 'Servicio'), ('OTRO', 'Otro')], default='ORDINARIO', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('presupuestado', models.BooleanField(default=False, help_text='Indica si el gasto estaba presupuestado')),
                ('recurrente', models.BooleanField(default=False, help_text='Indica si es un gasto que se repite periódicamente')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='financiero.categoriagasto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cuotas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_pagos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_recargos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='estados_cuenta/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuenta', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
                'ordering': ['-fecha_fin', 'vivienda'],
            },
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['vivienda', 'estado'], name='financiero__viviend_8baa71_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_pago'], name='financiero__fecha_p_aa91c4_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['categoria', 'fecha'], name='financiero__categor_5e02ee_idx'),
        ),
        migrations.AddIndex(
            model_name='gasto',
            index=models.Index(fields=['estado'], name='financiero__estado_3cdde8_idx'),
        ),
        migrations.AddIndex(
            model_name='estadocuenta',
            index=models.Index(fields=['vivienda', 'fecha_fin'], name='financiero__viviend_38bb72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estadocuenta',
            unique_together={('vivienda', 'fecha_inicio', 'fecha_fin')},
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['vivienda', 'pagada'], name='financiero__viviend_efde46_idx'),
        ),
        migrations.AddIndex(
            model_name='cuota',
            index=models.Index(fields=['fecha_vencimiento'], name='financiero__fecha_v_92cf81_idx'),
        ),
    ]
