# Generated by Django 4.2.10 on 2026-03-25 02:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
        ('financiero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('QR_BNB', 'QR BNB'), ('OTRO', 'Otro')], max_length=15),
        ),
        migrations.CreateModel(
            name='PagoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('glosa', models.CharField(max_length=200)),
                ('qr_id', models.CharField(help_text='ID del QR devuelto por BNB', max_length=100, unique=True)),
                ('qr_image', models.TextField(blank=True, help_text='Imagen QR en base64')),
                ('qr_estado', models.CharField(choices=[('GENERADO', 'QR Generado'), ('PAGADO', 'Pagado'), ('EXPIRADO', 'Expirado'), ('ERROR', 'Error')], default='GENERADO', max_length=15)),
                ('fecha_expiracion', models.DateField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuotas', models.ManyToManyField(related_name='pagos_qr', to='financiero.cuota')),
                ('pago', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_qr', to='financiero.pago')),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viviendas.residente')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_qr', to='viviendas.vivienda')),
            ],
            options={
                'verbose_name': 'Pago QR BNB',
                'verbose_name_plural': 'Pagos QR BNB',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['qr_estado', '-fecha_creacion'], name='financiero__qr_esta_abca9b_idx'), models.Index(fields=['vivienda', 'qr_estado'], name='financiero__viviend_d428b5_idx')],
            },
        ),
    ]
