# Generated by Django 4.2.10 on 2026-03-25 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financiero', '0002_add_pago_qr_bnb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BNB', 'Banco Nacional de Bolivia')], default='BNB', max_length=20)),
                ('numero_cuenta', models.CharField(help_text='Número de cuenta bancaria', max_length=30)),
                ('titular', models.CharField(help_text='Nombre del titular de la cuenta', max_length=200)),
                ('bnb_account_id', models.CharField(blank=True, help_text='accountId proporcionado por BNB (encriptado base64)', max_length=200)),
                ('bnb_authorization_id', models.CharField(blank=True, help_text='authorizationId proporcionado por BNB (encriptado base64)', max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('verificada', models.BooleanField(default=False, help_text='Se marca True cuando se valida la conexión con BNB exitosamente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('edificio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_bancaria', to='viviendas.edificio')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_bancarias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
    ]
