# Generated by Django 4.2.10 on 2026-03-25 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
        ('financiero', '0003_add_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='edificio',
            field=models.ForeignKey(blank=True, help_text='Edificio al que se asocia este gasto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='viviendas.edificio'),
        ),
    ]
