# Generated by Django 4.2.10 on 2025-05-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_reporte_fecha_desde_reporte_fecha_hasta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='es_favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reporte',
            name='puesto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
