# Generated by Django 4.2.10 on 2025-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_reporte_es_favorito_reporte_puesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('ACCESOS', 'Accesos'), ('RESIDENTES', 'Residentes'), ('VIVIENDAS', 'Viviendas'), ('PERSONAL', 'Personal'), ('FINANCIERO', 'Financiero')], max_length=20),
        ),
    ]
