# Generated by Django 4.2.10 on 2025-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reporte_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
