# Generated by Django 4.2.10 on 2025-05-22 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_reporte_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 22, 14, 21, 30, 416429, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
