# Generated by Django 4.2.10 on 2025-05-22 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
        ('reportes', '0006_reporte_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viviendas.edificio'),
        ),
    ]
