# Generated by Django 4.2.10 on 2025-05-28 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes', '0007_reporte_edificio'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='ultima_generacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
