# Generated by Django 4.2.10 on 2026-03-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_reporte_creado_por_reporte_ultima_generacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['tipo', 'activo'], name='reportes_re_tipo_82abba_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['es_favorito'], name='reportes_re_es_favo_6cb323_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['-fecha_creacion'], name='reportes_re_fecha_c_7e8e32_idx'),
        ),
    ]
