# Generated by Django 4.2.10 on 2025-05-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea puntual'), ('RESPONSABILIDAD', 'Responsabilidad recurrente')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
                ('prioridad', models.IntegerField(choices=[(1, 'Baja'), (2, 'Normal'), (3, 'Alta'), (4, 'Urgente')], default=2)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['-fecha_asignacion', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_especializacion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_contratacion', models.DateField()),
                ('tipo_contrato', models.CharField(choices=[('PERMANENTE', 'Permanente'), ('TEMPORAL', 'Temporal'), ('EXTERNO', 'Proveedor Externo')], default='PERMANENTE', max_length=15)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=150)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=15)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='personal.puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['usuario__last_name', 'usuario__first_name'],
            },
        ),
    ]
