# Generated by Django 4.2.10 on 2025-05-27 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=50)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historial de Asignación',
                'verbose_name_plural': 'Historiales de Asignaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora cuando se completó la asignación', null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='tiempo_estimado_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo estimado en horas', null=True),
        ),
        migrations.AddField(
            model_name='comentarioasignacion',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentarioasignacion',
            name='es_privado',
            field=models.BooleanField(default=False, help_text='Solo visible para administradores'),
        ),
        migrations.AddField(
            model_name='comentarioasignacion',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='puesto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el puesto está disponible para asignar'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='puesto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentarioasignacion',
            name='comentario',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['estado', '-fecha_asignacion'], name='personal_as_estado_afb047_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['empleado', '-fecha_asignacion'], name='personal_as_emplead_faa6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacion',
            index=models.Index(fields=['edificio', 'estado'], name='personal_as_edifici_7d50ed_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioasignacion',
            index=models.Index(fields=['asignacion', '-fecha'], name='personal_co_asignac_d8abe3_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioasignacion',
            index=models.Index(fields=['usuario', '-fecha'], name='personal_co_usuario_35cb91_idx'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.CheckConstraint(check=models.Q(('prioridad__gte', 1), ('prioridad__lte', 4)), name='asignacion_prioridad_valida'),
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.CheckConstraint(check=models.Q(('tiempo_estimado_horas__gte', 0), ('tiempo_estimado_horas__isnull', True), _connector='OR'), name='asignacion_tiempo_estimado_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(check=models.Q(('salario__gte', 0), ('salario__isnull', True), _connector='OR'), name='empleado_salario_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='puesto',
            constraint=models.CheckConstraint(check=models.Q(('nombre__isnull', False)), name='puesto_nombre_not_null'),
        ),
        migrations.AddField(
            model_name='historialasignacion',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='personal.asignacion'),
        ),
        migrations.AddField(
            model_name='historialasignacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historialasignacion',
            index=models.Index(fields=['asignacion', '-fecha'], name='personal_hi_asignac_4b077b_idx'),
        ),
    ]
