# Generated by Django 4.2.10 on 2025-06-01 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
        ('personal', '0003_add_audit_fields_compatible'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='viviendas.edificio'),
        ),
    ]
