# Generated by Django 4.2.10 on 2026-07-17 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('PLOMERIA', 'Plomeria'), ('ELECTRICIDAD', 'Electricidad'), ('ASCENSOR', 'Ascensor'), ('SEGURIDAD', 'Seguridad'), ('LIMPIEZA', 'Limpieza'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('REPORTADA', 'Reportada'), ('EN_REVISION', 'En revision'), ('APROBADA', 'Aprobada'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='REPORTADA', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='viviendas.residente')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='incidencias/evidencia/%Y/%m/%d/')),
                ('tipo', models.CharField(choices=[('FOTO', 'Foto'), ('VIDEO', 'Video'), ('DOCUMENTO', 'Documento')], default='FOTO', max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='incidencias.incidencia')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia de incidencia',
                'verbose_name_plural': 'Evidencias de incidencia',
                'ordering': ['fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='EventoIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CREADA', 'Incidencia creada'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('COMENTARIO', 'Comentario')], max_length=15)),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=15)),
                ('estado_nuevo', models.CharField(blank=True, default='', max_length=15)),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='incidencias.incidencia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de incidencia',
                'verbose_name_plural': 'Eventos de incidencia',
                'ordering': ['fecha'],
            },
        ),
    ]
