# Generated by Django 4.2.10 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estimacion_preliminar',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='idempotency_key',
            field=models.CharField(
                blank=True,
                help_text='Evita crear dos incidencias para una misma solicitud.',
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='ubicacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='urgencia',
            field=models.CharField(
                choices=[
                    ('BAJA', 'Baja'),
                    ('MEDIA', 'Media'),
                    ('ALTA', 'Alta'),
                    ('CRITICA', 'Crítica'),
                ],
                default='MEDIA',
                max_length=10,
            ),
        ),
    ]
