# Generated by Django 4.2.10 on 2026-07-19 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_empleado_edificio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidencias', '0002_incidencia_agent_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to='personal.empleado'),
        ),
        migrations.CreateModel(
            name='RevisionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('PLOMERIA', 'Plomeria'), ('ELECTRICIDAD', 'Electricidad'), ('ASCENSOR', 'Ascensor'), ('SEGURIDAD', 'Seguridad'), ('LIMPIEZA', 'Limpieza'), ('OTRO', 'Otro')], max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10)),
                ('costo_estimado_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_estimado_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('tiempo_estimado_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, default='')),
                ('origen', models.CharField(choices=[('AGENTE', 'Agente'), ('ADMINISTRADOR', 'Administrador'), ('TECNICO', 'Técnico')], max_length=15)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_incidencia_creadas', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='incidencias.incidencia')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=24, unique=True)),
                ('estado', models.CharField(choices=[('APROBADA', 'Aprobada'), ('PROGRAMADA', 'Programada'), ('EN_EJECUCION', 'En ejecución'), ('COMPLETADA', 'Completada')], default='APROBADA', max_length=15)),
                ('programada_inicio', models.DateTimeField(blank=True, null=True)),
                ('programada_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('incidencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orden_trabajo', to='incidencias.incidencia')),
                ('revision_aprobada', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='incidencias.revisionincidencia')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_trabajo', to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('mensaje', models.CharField(max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_incidencia', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='incidencias.incidencia')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AprobacionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RESIDENTE', 'Residente'), ('ADMINISTRADOR', 'Administrador'), ('TECNICO', 'Técnico')], max_length=15)),
                ('decision', models.CharField(choices=[('APROBADA', 'Aprobada'), ('REVISION_SOLICITADA', 'Revisión solicitada')], max_length=20)),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones', to='incidencias.revisionincidencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_incidencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='revisionincidencia',
            constraint=models.UniqueConstraint(fields=('incidencia', 'version'), name='incidencia_revision_version_unica'),
        ),
        migrations.AddIndex(
            model_name='notificacionincidencia',
            index=models.Index(fields=['destinatario', 'leida', '-fecha'], name='incidencias_destina_2efc25_idx'),
        ),
        migrations.AddConstraint(
            model_name='aprobacionincidencia',
            constraint=models.UniqueConstraint(fields=('revision', 'rol'), name='incidencia_aprobacion_rol_unica'),
        ),
    ]
