# Generated by Django 4.2.10 on 2026-03-18 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_maxima', models.PositiveIntegerField(default=20)),
                ('horario_inicio', models.TimeField(default='08:00')),
                ('horario_fin', models.TimeField(default='22:00')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='areas_comunes/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_comunes', to='viviendas.edificio')),
            ],
            options={
                'verbose_name': 'Area Comun',
                'verbose_name_plural': 'Areas Comunes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='areas_comunes.areacomun')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='viviendas.residente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha', '-hora_inicio'],
                'indexes': [models.Index(fields=['area_comun', 'fecha'], name='areas_comun_area_co_915f58_idx'), models.Index(fields=['residente', '-fecha'], name='areas_comun_residen_e26e07_idx')],
            },
        ),
    ]
