# Generated by Django 4.2.10 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas_comunes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="cantidad_personas",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reserva",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Evita crear dos reservas para una misma solicitud.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
