# Generated by Django 4.2.10 on 2025-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edificio',
            options={'ordering': ['nombre'], 'verbose_name': 'Edificio', 'verbose_name_plural': 'Edificios'},
        ),
        migrations.AlterModelOptions(
            name='residente',
            options={'ordering': ['vivienda__edificio__nombre', 'vivienda__numero', 'usuario__last_name'], 'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
        migrations.AlterModelOptions(
            name='vivienda',
            options={'ordering': ['edificio__nombre', 'piso', 'numero'], 'verbose_name': 'Vivienda', 'verbose_name_plural': 'Viviendas'},
        ),
        migrations.AlterUniqueTogether(
            name='vivienda',
            unique_together={('edificio', 'numero')},
        ),
        migrations.AddIndex(
            model_name='vivienda',
            index=models.Index(fields=['edificio', 'estado'], name='viviendas_v_edifici_40df72_idx'),
        ),
        migrations.AddIndex(
            model_name='vivienda',
            index=models.Index(fields=['activo', 'estado'], name='viviendas_v_activo_2db123_idx'),
        ),
    ]
