# Generated by Django 4.2.10 on 2026-07-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0002_alter_edificio_options_alter_residente_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificio',
            name='deptos_por_piso',
            field=models.PositiveIntegerField(default=0, help_text='Departamentos por piso para el generador (0 = manual).'),
        ),
        migrations.AddField(
            model_name='edificio',
            name='esquema_numeracion',
            field=models.CharField(choices=[('PISO_LETRA', 'Piso-Letra (1-A, 2-B)'), ('PISO_UNIDAD', 'Piso+Unidad (101, 202)'), ('CORRELATIVO', 'Correlativo (1, 2… / 001…)'), ('MANUAL', 'Manual (sin generador)')], default='MANUAL', help_text='Convención de numeración que usa el generador de viviendas.', max_length=12),
        ),
    ]
