# Generated by Django 4.2.10 on 2026-07-17 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viviendas', '0003_edificio_deptos_por_piso_edificio_esquema_numeracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='condominio',
            field=models.ForeignKey(blank=True, help_text='Condominio/lugar al que pertenece esta torre (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='edificios', to='viviendas.condominio'),
        ),
    ]
